import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

const migrationUrl = new URL(
  "../../backend/database/migrations/20260813_0001_repair_playlist_provider_metadata.sql",
  import.meta.url,
);
const migration = readFileSync(migrationUrl, "utf8");
const updates = migration
  .trim()
  .split(/;\s*(?=UPDATE profile_modules)/u)
  .map((statement) => statement.trim());

describe("playlist provider metadata repair migration", () => {
  it("updates every recognized playlist provider without replacing config JSON", () => {
    expect(updates).toHaveLength(3);

    for (const statement of updates) {
      expect(statement).toMatch(/^UPDATE profile_modules\nSET config_json = CASE/u);
      expect(statement).toContain("ELSE JSON_SET(");
      expect(statement).toContain("'$.platform'");
      expect(statement).toContain("'$.sourceMode'");
      expect(statement).toContain("'music_playlist'");
      expect(statement).toContain("'spotify_playlist'");
      expect(statement).toContain("'apple_music_playlist'");
      expect(statement).toContain("'youtube_music_playlist'");
      expect(statement).toContain("'youtube_playlist'");
    }

    expect(migration).toContain("open[.]spotify[.]com([/?#]|$)");
    expect(migration).toContain("(music|itunes)[.]apple[.]com([/?#]|$)");
    expect(migration).toContain("youtube[.]com([/?#]|$)");
    expect(migration).toContain("youtu[.]be([/?#]|$)");
  });

  it("only relabels internally consistent autogenerated provider labels", () => {
    expect(migration.match(/WHEN title IS NULL/gu)).toHaveLength(3);
    expect(migration).toContain(
      "JSON_UNQUOTE(JSON_EXTRACT(config_json, '$.label')) = 'Apple Music playlist'",
    );
    expect(migration).toContain(
      "JSON_UNQUOTE(JSON_EXTRACT(config_json, '$.platform')) = 'apple_music'",
    );
    expect(migration).toContain(
      "JSON_UNQUOTE(JSON_EXTRACT(config_json, '$.sourceMode')) = 'apple_music'",
    );
    expect(migration).not.toContain(
      "JSON_UNQUOTE(JSON_EXTRACT(config_json, '$.label')) = 'Playlist'",
    );
  });

  it("cannot mutate titles, layout, visibility, status, tracks, or other config keys", () => {
    expect(migration).not.toMatch(/SET\s+(?:title|visibility|position|status|schema_version|grid_)/u);
    expect(migration).not.toContain("'$.tracks'");
    expect(migration).not.toContain("'$.canvasSize'");
    expect(migration).not.toContain("'$.configured'");

    const assignedPaths = [...migration.matchAll(/\n\s+'(\$\.[A-Za-z]+)',\n/gu)]
      .map((match) => match[1]);
    expect(new Set(assignedPaths)).toEqual(
      new Set(["$.label", "$.platform", "$.sourceMode"]),
    );
  });
});
